# hold constant and utility functions

france_region_adjacency = [
    ('FR-A', 'FR-M'),
    ('FR-A', 'FR-I'),
    ('FR-B', 'FR-T'),
    ('FR-B', 'FR-L'),
    ('FR-B', 'FR-N'),
    ('FR-C', 'FR-F'),
    ('FR-C', 'FR-D'),
    ('FR-C', 'FR-V'),
    ('FR-C', 'FR-K'),
    ('FR-C', 'FR-N'),
    ('FR-C', 'FR-L'),
    ('FR-D', 'FR-J'),
    ('FR-D', 'FR-G'),
    ('FR-D', 'FR-I'),
    ('FR-D', 'FR-V'),
    ('FR-D', 'FR-F'),
    ('FR-E', 'FR-P'),
    ('FR-E', 'FR-R'),
    ('FR-F', 'FR-Q'),
    ('FR-F', 'FR-J'),
    ('FR-F', 'FR-L'),
    ('FR-F', 'FR-T'),
    ('FR-F', 'FR-R'),
    ('FR-F', 'FR-P'),
    ('FR-G', 'FR-M'),
    ('FR-G', 'FR-I'),
    ('FR-G', 'FR-J'),
    ('FR-G', 'FR-S'),
    # no adjacent region for FR-H
    ('FR-I', 'FR-M'),
    ('FR-I', 'FR-V'),
    ('FR-J', 'FR-S'),
    ('FR-J', 'FR-Q'),
    ('FR-K', 'FR-V'),
    ('FR-K', 'FR-U'),
    ('FR-K', 'FR-N'),
    ('FR-L', 'FR-N'),
    ('FR-L', 'FR-T'),
    ('FR-O', 'FR-S'),
    ('FR-P', 'FR-Q'),
    ('FR-P', 'FR-R'),
    ('FR-Q', 'FR-S'),
    ('FR-R', 'FR-T'),
    ('FR-U', 'FR-V'),
]